version: "3.8"

services:
    app-subscription-service:
        build: .
        volumes:
            - .:/app
        networks:
            - main
        command: ./mvnw spring-boot:run
        ports:
            - "8080:8080"
        depends_on:
            - api-nameserver
        environment:
            - eureka.client.serviceUrl.defaultZone=http://api-nameserver:8761/eureka
networks:
    main:
        driver: bridge
